
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # This is a public key, safe to be exposed in the client bundle.
  # We are telling Netlify's secret scanner to ignore it.
  NEXT_PUBLIC_FIREBASE_API_KEY = "dummy_value_for_build"

[functions]
  # This is required for the Netlify Next.js runtime to work correctly.
  node_bundler = "esbuild"
