# Exported from Render on 2025-12-27T00:23:49Z
version: "1"
projects:
- name: SmartEtudesCI
  environments:
  - name: Production
    services:
    - type: web
      name: smartetude
      runtime: node
      repo: https://github.com/dreaminterpretsite-collab/smartetude
      plan: free
      envVars:
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: PORT
        sync: false
      region: virginia
      buildCommand: npm install; npm run build
      startCommand: npm run start
      domains:
      - smart-etudes.com
      - www.smart-etudes.com
      autoDeployTrigger: commit
